# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .platypus import *
from .provider import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "animals",
  "mod": "index",
  "fqn": "pulumi_animals",
  "classes": {
   "animals:index:Platypus": "Platypus"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "animals",
  "token": "pulumi:providers:animals",
  "fqn": "pulumi_animals",
  "class": "Provider"
 }
]
"""
)
